[package]
name = "kittymc-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
kittymc-lib = { path = "../kittymc_lib" }
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros", "net", "io-util"] }
anyhow = "1.0.94"
